### ISSUE TITLE
Are you still around here?

### ISSUE THREAD

**Issue by msmilkshake** [OpenPop/OpenPopulous#1]
As the title say, are you still around?

**Comment by w3bdesign** [comment]
I assume that this project has been abondoned. :(

**Comment by aidanhs** [comment]
Hello! I'm still here.

But I just want to point out the description of this repo - I'm not the creator, this is just a mirror from a sourceforge repository. The same is true of most of the repos under this org - I want to save them from bitrotting off the internet.

I think it's safe to say this repository is not going to be updated given the last commit was in 2011 - the original creator (@IntelOrca) looks like they had another brief stab in 2014/2014 (https://github.com/IntelOrca/popss), but they seem to be pretty actively working on https://openrct2.io/ now (and doing an awesome job of it!).

**Comment by IntelOrca** [comment]
I will also add that there is a hidden closed source project being worked on for Populous 3 which is beyond complete but I can't give any more details on it as I no longer have access to the project sources.

http://www.populous3.info/bugs/my_view_page.php

**Comment by aidanhs** [comment]
Huh, really interesting, thanks @IntelOrca.

I've been out of it for a while, but it looks like somehow the original source was acquired(!) around 2015 and it's been quietly worked on at https://github.com/Brandantl/Populous-The-Beginning/ (private repo) since then. Betas look like they get posted semiregularly on popre.net.

Seems promising, will have to keep half an eye on it.

**Comment by TylerTheFox** [comment]
PopRe's projects are coordinated and handled through our Discord which you can join from this link. https://discord.gg/u474HpE

**Comment by jamescporter** [comment]
Was the original source actually acquired? I am interested in getting involved in some of the work

**Comment by IntelOrca** [comment]
@jamescporter yes, you can probably join the development team at the discord linked above. It would be nice if it was open source though.

**Comment by msmilkshake** [comment]
I hanged with the discord community for a few days and I have to say that they're all amazing!!
