### ISSUE TITLE
Help to compile the project

### ISSUE THREAD

**Issue by ghost** [OpenPop/OpenPopulous#2]
Hello everybody, if is there anyone watching on this repo, I just want some help to compile the project ! Thanks

**Comment by aidanhs** [comment]
Hi, please see the (brief) discussion on https://github.com/OpenPop/OpenPopulous/issues/1 - this repo is primarily intended as a mirror. If you get it working then great and please let me know! But I wouldn't spend too much time trying to resurrect it.
